### ISSUE TITLE
ERROR:root:<class 'pexpect.pxssh.ExceptionPxssh'>: Could not establish connection to host

### ISSUE THREAD

**Issue by katmai** [OpenDevin/OpenDevin#1050]
#### Describe the bug
doesn't start on the latest build. i assume the container names got changed, because the container is running.

```
atlas@chia01:~$ docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS          PORTS     NAMES
7bded603fe1d   ghcr.io/opendevin/sandbox   "/usr/sbin/sshd -D -…"   37 seconds ago   Up 36 seconds             opendevin-sandbox-default

```

#### Setup and configuration
**Current version**:

```
commit 494a1b6872696ae9f56ef7e4c2bd7ad0a7ee2641 (HEAD -> main, origin/main, origin/HEAD)
Author: Leo <ifuryst@gmail.com>
Date:   Fri Apr 12 19:53:47 2024 +0800

    Feat add agent manager (#904)

    * feat: add agent manager to manage all agents;

    * extract the host ssh port to prevent conflict.

    * clean all containers with prefix is sandbox-

    * merge from upstream/main

    * merge from upstream/main

    * Update frontend/src/state/settingsSlice.ts

    * Update opendevin/sandbox/ssh_box.py

    * Update opendevin/sandbox/exec_box.py

    ---------

    Co-authored-by: Robert Brennan <accounts@rbren.io>

```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1.
2.
3.

**Logs, error messages, and screenshots**:
```
Running OpenDevin via CLI...
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Running agent MonologueAgent (model: ollama/dolphin-mixtral:latest, directory: ./workspace/) with task: "write a bash script that prints hi"
13:57:23 - opendevin:INFO: ssh_box.py:80 - Using workspace directory: /home/atlas/OpenDevin/workspace
13:57:24 - opendevin:INFO: ssh_box.py:280 - Container stopped
13:57:24 - opendevin:INFO: ssh_box.py:312 - Container started
13:57:25 - opendevin:INFO: ssh_box.py:329 - waiting for container to start: 1, container status: running
13:57:26 - opendevin:INFO: ssh_box.py:169 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password 'fd1136ad-3880-4079-9c3b-c8fadc400644' and report the issue on GitHub.
ERROR:root:  File "/home/atlas/OpenDevin/opendevin/main.py", line 96, in <module>
    asyncio.run(main())
  File "/home/atlas/.pyenv/versions/3.11.3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/atlas/.pyenv/versions/3.11.3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/.pyenv/versions/3.11.3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/atlas/OpenDevin/opendevin/main.py", line 88, in main
    controller = AgentController(
                 ^^^^^^^^^^^^^^^^
  File "/home/atlas/OpenDevin/opendevin/controller/agent_controller.py", line 88, in __init__
    self.command_manager = CommandManager(self.id, workdir, container_image)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/OpenDevin/opendevin/controller/command_manager.py", line 26, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/atlas/OpenDevin/opendevin/sandbox/ssh_box.py", line 98, in __init__
    self.start_ssh_session()
  File "/home/atlas/OpenDevin/opendevin/sandbox/ssh_box.py", line 174, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')

ERROR:root:<class 'pexpect.pxssh.ExceptionPxssh'>: Could not establish connection to host

```

**Comment by andrewparry** [comment]
Could be connected. I get a permission denied if I try and login to the server using this method. 
`08:41:31 - opendevin:INFO: ssh_box.py:169 - ConnectinI get a permission denied if I try and login to the server:
`08:41:31 - opendevin:INFO: ssh_box.py:169 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password '517c8bd0-6d2d-4954-a9e9-ce722ee47a0e' and report the issue on GitHub.
`g to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password '517c8bd0-6d2d-4954-a9e9-ce722ee47a0e' and report the issue on GitHub.
`

**Comment by iFurySt** [comment]
> Could be connected. I get a permission denied if I try and login to the server using this method.
> 
> ```
> 08:41:31 - opendevin:INFO: ssh_box.py:169 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password '517c8bd0-6d2d-4954-a9e9-ce722ee47a0e' and report the issue on GitHub.
> ```

yes, i also found it, cuz it prints the wrong port number. the port number 2222 is inside the container. i'll submit a PR later.

**Comment by iFurySt** [comment]
@katmai hi, do you mind providing more context about how to reproduce this problem?

**Comment by wolfhoundjesse** [comment]
This solution, with added quotation marks, worked for me.
https://github.com/OpenDevin/OpenDevin/issues/982#issuecomment-2048482341

**Comment by katmai** [comment]
> @katmai hi, do you mind providing more context about how to reproduce this problem?

pulled the last commit from the repo and after running "make build" i just start OpenDevin by using: "cd ~/OpenDevin/ && poetry run python opendevin/main.py -d ./workspace/ -t "write a bash script that prints hi""

then i had the error.

**Comment by katmai** [comment]
i can confirm that adding 
SANDBOX_TYPE="exec" to config.toml gets it to work.

**Comment by ack72tdp** [comment]
Not worked for me quite even after adding SANDBOX_TYPE

Running the app...
Starting backend server...
Waiting for the backend to start...
/home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [5295]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> vite --port 3001


  VITE v5.2.8  ready in 289 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
INFO:     127.0.0.1:54728 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:54746 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:54748 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:54734 - "GET /configurations HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 54760) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIzY2ZiNjY3ZC1iM2UyLTQ3ODEtOWVmOC0xMWU0NjM0OWM2NGIifQ._IZw3qGr0HECzv3WY1gAahoqOYEo5NAxO0o21QkoFH4" [accepted]
Starting loop_recv for sid: 3cfb667d-b3e2-4781-9ef8-11e46349c64b
INFO:     connection open
INFO:     127.0.0.1:54774 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:54764 - "GET /configurations HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 54778) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIzY2ZiNjY3ZC1iM2UyLTQ3ODEtOWVmOC0xMWU0NjM0OWM2NGIifQ._IZw3qGr0HECzv3WY1gAahoqOYEo5NAxO0o21QkoFH4" [accepted]
Starting loop_recv for sid: 3cfb667d-b3e2-4781-9ef8-11e46349c64b
INFO:     connection open
INFO:     127.0.0.1:54804 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:54790 - "GET /configurations HTTP/1.1" 200 OK
12:34:29 - opendevin:INFO: exec_box.py:75 - Using workspace directory: /home/chadaa/OpenDevin/workspace
12:34:29 - opendevin:INFO: exec_box.py:198 - Container stopped
12:34:29 - opendevin:INFO: exec_box.py:215 - Container started
INFO:     ('127.0.0.1', 54820) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIzY2ZiNjY3ZC1iM2UyLTQ3ODEtOWVmOC0xMWU0NjM0OWM2NGIifQ._IZw3qGr0HECzv3WY1gAahoqOYEo5NAxO0o21QkoFH4" [accepted]
Starting loop_recv for sid: 3cfb667d-b3e2-4781-9ef8-11e46349c64b
INFO:     connection open
INFO:     127.0.0.1:54834 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:54830 - "GET /configurations HTTP/1.1" 200 OK
12:34:30 - opendevin:ERROR: session.py:44 - Error in loop_recv: cannot call recv while another coroutine is already waiting for the next message
Traceback (most recent call last):
  File "/home/chadaa/OpenDevin/opendevin/server/session/session.py", line 29, in loop_recv
    data = await self.websocket.receive_json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.11/site-packages/starlette/websockets.py", line 157, in receive_json
    message = await self.receive()
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.11/site-packages/starlette/websockets.py", line 49, in receive
    message = await self._receive()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 379, in asgi_receive
    data = await self.recv()
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 533, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message
^CReceived signal 2, exiting...

This is on Ubuntu virtual environment running in Windows 11 with WSL ..  Any thoughts?

without SANDBOX_TYPE  .. it used to prompt me for ssh .. and ssh worked fine and it logged into that system ...

**Comment by katmai** [comment]
> Not worked for me quite even after adding SANDBOX_TYPE
> 
> Running the app... Starting backend server... Waiting for the backend to start... /home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".
> 
> You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`. warnings.warn( /home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".
> 
> You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`. warnings.warn( /home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".
> 
> You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`. warnings.warn( /home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".
> 
> You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`. warnings.warn( /home/ubuntu/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".
> 
> You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`. warnings.warn( INFO: Started server process [5295] INFO: Waiting for application startup. INFO: Application startup complete. INFO: Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit) Backend started successfully. Starting frontend with npm...
> 
> > opendevin-frontend@0.1.0 start
> > vite --port 3001
> 
> VITE v5.2.8 ready in 289 ms
> 
> ➜ Local: http://localhost:3001/ ➜ Network: use --host to expose ➜ press h + enter to show help INFO: 127.0.0.1:54728 - "GET /refresh-files HTTP/1.1" 200 OK INFO: 127.0.0.1:54746 - "GET /messages/total HTTP/1.1" 200 OK INFO: 127.0.0.1:54748 - "GET /refresh-files HTTP/1.1" 200 OK INFO: 127.0.0.1:54734 - "GET /configurations HTTP/1.1" 200 OK INFO: ('127.0.0.1', 54760) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIzY2ZiNjY3ZC1iM2UyLTQ3ODEtOWVmOC0xMWU0NjM0OWM2NGIifQ._IZw3qGr0HECzv3WY1gAahoqOYEo5NAxO0o21QkoFH4" [accepted] Starting loop_recv for sid: 3cfb667d-b3e2-4781-9ef8-11e46349c64b INFO: connection open INFO: 127.0.0.1:54774 - "GET /messages/total HTTP/1.1" 200 OK INFO: 127.0.0.1:54764 - "GET /configurations HTTP/1.1" 200 OK INFO: ('127.0.0.1', 54778) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIzY2ZiNjY3ZC1iM2UyLTQ3ODEtOWVmOC0xMWU0NjM0OWM2NGIifQ._IZw3qGr0HECzv3WY1gAahoqOYEo5NAxO0o21QkoFH4" [accepted] Starting loop_recv for sid: 3cfb667d-b3e2-4781-9ef8-11e46349c64b INFO: connection open INFO: 127.0.0.1:54804 - "GET /messages/total HTTP/1.1" 200 OK INFO: 127.0.0.1:54790 - "GET /configurations HTTP/1.1" 200 OK 12:34:29 - opendevin:INFO: exec_box.py:75 - Using workspace directory: /home/chadaa/OpenDevin/workspace 12:34:29 - opendevin:INFO: exec_box.py:198 - Container stopped 12:34:29 - opendevin:INFO: exec_box.py:215 - Container started INFO: ('127.0.0.1', 54820) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIzY2ZiNjY3ZC1iM2UyLTQ3ODEtOWVmOC0xMWU0NjM0OWM2NGIifQ._IZw3qGr0HECzv3WY1gAahoqOYEo5NAxO0o21QkoFH4" [accepted] Starting loop_recv for sid: 3cfb667d-b3e2-4781-9ef8-11e46349c64b INFO: connection open INFO: 127.0.0.1:54834 - "GET /messages/total HTTP/1.1" 200 OK INFO: 127.0.0.1:54830 - "GET /configurations HTTP/1.1" 200 OK 12:34:30 - opendevin:ERROR: session.py:44 - Error in loop_recv: cannot call recv while another coroutine is already waiting for the next message Traceback (most recent call last): File "/home/ubuntu/venv/opendevin/server/session/session.py", line 29, in loop_recv data = await self.websocket.receive_json() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/ubuntu/venv/lib/python3.11/site-packages/starlette/websockets.py", line 157, in receive_json message = await self.receive() ^^^^^^^^^^^^^^^^^^^^ File "/home/ubuntu/venv/lib/python3.11/site-packages/starlette/websockets.py", line 49, in receive message = await self._receive() ^^^^^^^^^^^^^^^^^^^^^ File "/home/ubuntu/venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 379, in asgi_receive data = await self.recv() ^^^^^^^^^^^^^^^^^ File "/home/ubuntu/venv/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 533, in recv raise RuntimeError( RuntimeError: cannot call recv while another coroutine is already waiting for the next message ^CReceived signal 2, exiting...
> 
> This is on Ubuntu virtual environment running in Windows 11 with WSL .. Any thoughts?
> 
> without SANDBOX_TYPE .. it used to prompt me for ssh .. and ssh worked fine and it logged into that system ...

https://github.com/OpenDevin/OpenDevin/issues/995

i followed the suggestions and chose to ditch the front end momentarily. see if this might be of use to you.
