### ISSUE TITLE
`make run` failed with `libcudart.so.12: cannot open shared object file`

### ISSUE THREAD

**Issue by functicons** [OpenDevin/OpenDevin#726]
#### Describe the bug

`make run` failed with `OSError: libcudart.so.12: cannot open shared object file: No such file or directory`

#### Setup and configuration
**Current version**:

```bash
$ git log -n 1
commit baa981cda761907ae53419921e1aa5d8048d18d9 (HEAD -> main, upstream/main, origin/main, origin/HEAD)
Author: mashiro <github@te.sb>
Date:   Thu Apr 4 21:44:07 2024 +0800

    fix: block input send event while ime composition (#701)
    
    * fix: trigger send event while ime composition & separate input element & disable input event while initializing
    
    * fix: eslint react plugin setting
    
    ---------
    
    Co-authored-by: Jim Su <jimsu@protonmail.com>
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

**Steps to Reproduce**:
1. make build
2. make run

**Logs, error messages, and screenshots**:

$ make run
Running the app...
make[1]: Entering directory '/repo/github/functicons/OpenDevin'
Starting backend...
make[1]: Entering directory '/repo/github/functicons/OpenDevin'
Starting frontend...

> opendevin-frontend@0.1.0 start
> vite

  VITE v5.2.8  ready in 519 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
Traceback (most recent call last):
  File "/.local/share/virtualenvs/OpenDevin-fz-TgslG/lib/python3.11/site-packages/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.local/share/virtualenvs/OpenDevin-fz-TgslG/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/.local/share/virtualenvs/OpenDevin-fz-TgslG/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/share/virtualenvs/OpenDevin-fz-TgslG/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/.local/share/virtualenvs/OpenDevin-fz-TgslG/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/share/virtualenvs/OpenDevin-fz-TgslG/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/share/virtualenvs/OpenDevin-fz-TgslG/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/.local/share/virtualenvs/OpenDevin-fz-TgslG/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/.local/share/virtualenvs/OpenDevin-fz-TgslG/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

**Comment by 6b3478** [comment]
```
function install_python() {
        ver="$1" ; if [[ -z "$ver" ]] || [[ "$ver" = "-h" ]] || [[ "$ver" = "--help" ]]
        then
                curl -fsSL https://www.python.org/ftp/python > /tmp/pv && \
                pvs=$(egrep -o '"([^"]*)"' /tmp/pv | grep '[0-9]' | grep -v '[a-z]' | sed 's+"\|/++g'  | tr '\n' ' ') && \
                printf "Usage: $0 VERSION\n\nVersions: $pvs\n"  && exit 0
        fi

        function __install_python(){
                apt-get install -y build-essential
                apt-get install -y uuid-dev tk-dev liblzma-dev libgdbm-dev libsqlite3-dev \
                libbz2-dev libreadline-dev zlib1g-dev libncursesw5-dev libssl-dev libffi-dev

                rm -r /tmp/Python* 2> /dev/null ; curl -kfSL https://www.python.org/ftp/python/$ver/Python-$ver.tgz | \
                tar xzv -C /tmp/ -- && cd /tmp/Python-$ver

                ./configure --enable-optimizations --enable-shared CC=clang CXX=clang++

                make -j$(nproc) ; make altinstall ; ldconfig
                python$(echo $ver|cut -d. -f1-2) <(curl -sL https://bootstrap.pypa.io/get-pip.py)
        }

        __install_python $ver
}
```

install_python 3.10.9 ; sed -i 's+python+python3.10+g' Makefile ; rm Pipfile.lock ; make build

**Comment by rahulraikwar00** [comment]
Ensure that you have already installed the NVIDIA CUDA toolkit. If you have not yet installed it, please refer to the official NVIDIA documentation for a step-by-step guide on how to install the CUDA toolkit on  your system 
 https://docs.nvidia.com/cuda/wsl-user-guide/index.html.

**Comment by gabrielfgularte** [comment]
> ```
> function install_python() {
>         ver="$1" ; if [[ -z "$ver" ]] || [[ "$ver" = "-h" ]] || [[ "$ver" = "--help" ]]
>         then
>                 curl -fsSL https://www.python.org/ftp/python > /tmp/pv && \
>                 pvs=$(egrep -o '"([^"]*)"' /tmp/pv | grep '[0-9]' | grep -v '[a-z]' | sed 's+"\|/++g'  | tr '\n' ' ') && \
>                 printf "Usage: $0 VERSION\n\nVersions: $pvs\n"  && exit 0
>         fi
> 
>         function __install_python(){
>                 apt-get install -y build-essential
>                 apt-get install -y uuid-dev tk-dev liblzma-dev libgdbm-dev libsqlite3-dev \
>                 libbz2-dev libreadline-dev zlib1g-dev libncursesw5-dev libssl-dev libffi-dev libllvm-dev clang
> 
>                 rm -r /tmp/Python* 2> /dev/null ; curl -kfSL https://www.python.org/ftp/python/$ver/Python-$ver.tgz | \
>                 tar xzv -C /tmp/ -- && cd /tmp/Python-$ver
> 
>                 ./configure --enable-optimizations --enable-shared CC=clang CXX=clang++
> 
>                 make -j$(nproc) ; make altinstall ; ldconfig
>                 python$(echo $ver|cut -d. -f1-2) <(curl -sL https://bootstrap.pypa.io/get-pip.py)
>         }
> 
>         __install_python $ver
> }
> ```
> 
> install_python 3.10.9 ; sed -i 's+python+python3.10+g' Makefile ; rm Pipfile.lock ; make build

Could you explain why your code is doing? Why are you installing python 3.10 if the requirements specifies 3.11?

**Comment by foragerr** [comment]
OpenDevin doesn't use it, it's likely a transitive dependency of some dependency OpenDevin uses. My strongest suspect is `torch`

**Comment by beduffy** [comment]
I had the same problem, to make it work I uninstalled torch, deleted Pipfile.lock and renamed Pipfile.torchidx to Pipfile.

**Comment by soumyamaity** [comment]
same problem

**Comment by soumyamaity** [comment]
SOLVED!


To activate this project's virtualenv, run `pipenv shell`.
Alternatively, run a command inside the virtualenv with `pipenv run make run`.

**Comment by soumyamaity** [comment]
Solved by installing torch.
`pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/torch_stable.html'

**Comment by dorbanianas** [comment]
can you try to pull the new main and let me know if there's any updates

**Comment by functicons** [comment]
> can you try to pull the new main and let me know if there's any updates

I am not able to verify it now, because the project just switched to Peotry from Pipenv, and there are errors when with Peotry.

**Comment by dorbanianas** [comment]
you can now pull the latest main, and try to run `make build` if you get some errors you can send the logs here

**Comment by rbren** [comment]
Should be fixed with the new docker installation method
